### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "Marcos Vinicius",
    "matricula" : "lu12353",
    "cpf" : "2",
    "telefone" : "tel2383738",
    "grupo" : 1,
    "senha" : "2231ivbiscoito"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Marcos Vinicius Arruda Vandresen",
    "matricula" : "lu12353",
    "cpf" : "23",
    "telefone" : "tel2383738",
    "grupo" : 1,
    "senha" : "segredo"
} 

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1